citation-style-language/schema

- csl-citation.json
- csl-data.json
The goal is to allow validators to detect which draft to use, without having to hardcode it in downstream applications. For example, I want my application to use the latest CSL Items schema and to continue working even if this repository upgrades to a newer schema draft.
> Specify draft via $schema in JSON schema

- csl-data.rnc
ab8f90ddeb9824028e86a0cd86f6e1e4986d1c6b had renamed the definitions, so the file doesn't work in 1.0.1.
> Fix references

- csl-data.json
Closes https://github.com/citation-style-language/schema/issues/154
I verified the following executed without error (but have not done further testing):
```python
import jsonref
import jsonschema
url = 'https://github.com/dhimmel/schema/raw/01d112e0ba606c4f61fcc9e27e4f623f5aad8da6/csl-data.json'
schema = jsonref.load_uri(url, jsonschema=True)
jsonschema.Draft3Validator.check_schema(schema)
```
Another question is whether there is a larger simplification that can be made. Should type remain a list in these instances?
> Remove duplicate literal types

- .github/workflows/test.yaml
- .travis.yml
Haven't test this yet... will update with whether it works.
I find GitHub actions is a bit slicker than Travis and is nicely integrated with GitHub. If we merge this, could then remove Travis.
> add github actions test workflow

- csl.rnc
Supports definition of AuthorOnly rendering required to assemble
intext (aka narrative, or textual) citations.
Closes #141.
> add new cs:intext element

- csl.rnc
`and="text"` -> `and="long"`; makes clear rendering for "and" should be based on term definition, and so also to allow configuration of `and="symbol"`.
closes #137
> Change "and" to allow "short", use term

- schemas/styles/csl.rnc
This removes the deprecated "template" and "independent-parent"
attribute values, and closes #58.
> Remove deprecated attribute values

- .github/ISSUE_TEMPLATE/feature_request.md
Not really sure exactly what these should be in the end, but this is a start.
It's designed to address the biggest thing historically missing from issue requests (missing context, including style guide links). 
Note, though, I only tweaked the default template, so not sure.
Please review this "feature request" template, and also weigh in on if you think we need others (like "bug report"), and if so, what the content should be.
> Add issue templates

- schemas/input/csl-data.json
- schemas/styles/csl-variables.rnc
`translated-title` is a translation of a different-lanugage title (e.g., to provide an English translation of a Spanish title in an English-locale bibliography). For example, this is the APA format for an item with a non-English title:
Chaves-Morillo, V., Gómez Calero, C., Fernández-Muñoz, J. J., Toledano-Muñoz, A., Fernández-Huete, J., Martínez-Monge, N., Palacios-Ceña, D., & Peñacoba-Puente, C. (2017). La anosmia neurosensorial: Relación entre subtipo, tiempo de reconocimiento y edad [Sensorineural anosmia: Relationship between subtype, recognition time, and age]. _Clínica y Salud, 28_(3), 155–161. https://doi.org/10.1016/j.clysa.2017.04.002
This is not intended to provide full multilingual support ala CSLm.
Addresses the `translated-title` discussion here: …
> Add translated-title

- schemas/input/csl-data.json
- schemas/styles/csl-variables.rnc
The curator of a collection or exhibition. Used when citing an exhibition catalog or an entry in such a catalog.
https://forums.zotero.org/discussion/17338
https://forums.zotero.org/discussion/13142/exhibition-catalogue
https://forums.zotero.org/discussion/comment/344317#Comment_344317
> Add curator variable

- schemas/styles/csl.rnc
We expect data to be input in sentence case because reliably converting to sentence case isn't possible without BibTeX-style escaping. Will remove in v1.1.
> Deprecate sentence case

- schemas/styles/csl-types.rnc
Add type `event` for citations directly to exhibitions, conferences, etc.
Fixes # https://github.com/citation-style-language/schema/issues/208#issuecomment-646954989
> Add event type

- schemas/styles/csl-terms.rnc
Some style require descriptive terms added for certain item types. This poses challenges for localization. This adds a term for every item type to `csl-terms.rnc`.
Fixes https://github.com/citation-style-language/schema/issues/178
See also https://github.com/citation-style-language/zotero-bits/issues/70
> Item type terms

- schemas/styles/csl-choose.rnc
- schemas/styles/csl.rnc
This adds a modified version of the CSL-M condition element as an option
to configure more complex conditional rules.
Also splits off the cs:choose section into a separate file.
Closes #255
Could people please test this, both the actual code, and also the docstrings, in a validating edtior (like Atom), and post feedback?
Will it be totally clear for style authors how this would work if we merge this?
> Add new cs:condition element to choose

- schemas/input/csl-data.json
- schemas/styles/csl-variables.rnc
Regarding `reviewed-genre`, it's the major variable that is missing from being able to describe what type of review a `review` item is. Most reviews could be reasonably be handled with this variable and the existing `reviewed-` variables. Better support for non-book `original-` items requires too many individual variables.
_Originally posted by @bwiernik in https://github.com/citation-style-language/schema/issues/167#issuecomment-647803302_
Please also include relevant motivation and context, on a separate line.
> add reviewed-genre variable

- schemas/input/csl-data.json
- schemas/styles/csl-variables.rnc
This adds `citekey` to csl-data.json and csl-variables.rnc.
This should make switching from word-processors to plain text based systems (pandoc, latex) easier.
Closes #243
Do we need to add this also to csl-citation.json in addition to `id` [here](https://github.com/citation-style-language/schema/blob/68dff7c3d9906a7dc915b06409353e5ad28b8506/schemas/input/csl-citation.json#L24).
> adds citekey variable to csl-data.json and csl-variables.rnc

- schemas/styles/csl-variables.rnc
- schemas/styles/csl.rnc
This moves specification of split title components from dedicated variables to new "sub" and "main" `@form` values.
Removes the -short title variable variants as well.
> Add sub/main form values to cs:text

- schemas/styles/csl-variables.rnc
What it says: Move `section` to numbers. Makes `label="section"` available.
> Move "section", "version" strings to numbers

- schemas/styles/csl-variables.rnc
Add editor-translator to the RNC schema to make it a testable variable. This makes it possible to modify the formatting of editor and translator depending on if they are the same person or not. The variable itself is still populated by the processor collapsing editor and translator.
This would require a minor update to processor code. They already have the editortranslator collapsing code; but they would likely need a small modification to call it during and if test. Given that, probably v1.1, rather than 1.0.2?
Fixes part of # citation-style-language/csl-evolution#7
> Add editor-translator as testable variable

- schemas/input/csl-data.json
- schemas/styles/csl-variables.rnc
Remove the date variable `container`, which doesn't make much of any sense.
Closes # https://github.com/citation-style-language/documentation/pull/41
- (Need to remove `container` from a small number of repo styles.)
> Remove `container`

- schemas/input/csl-data.json
closes https://github.com/citation-style-language/schema/issues/277
let me know if any other files need to be changed. I added `title` and `description` as per #190. Hopefully we can eventually auto-generate CSL JSON docs from this... but are there docs that need to be updated manually now?
> CSL JSON Data schema: add custom field

- schemas/styles/csl-terms.rnc
This adds two additional locators: `act` and `scene`.
This were still missing.
Clsoes https://github.com/citation-style-language/schema/issues/288
> Add act and scene locators

- schemas/input/csl-data.json
As part of #278, and to harmonize the JSON and YAML representations around a much more concise and expressive date format, this adds an option to use [EDTF](https://www.loc.gov/standards/datetime/).
While [EDTF](https://www.loc.gov/standards/datetime/) was originally an initiative of the US Library of Congress, it seems that in 2019, ISO adopted it as part of [8601-2](https://www.iso.org/obp/ui/#iso:std:iso:8601:-2:ed-1:v1:en).
Example of a date-range with a circa qualifier in the new alternative (using the YAML syntax):
``` yaml
issued: 2004-02-01/2005-02-08?
```
-----
1. settle on the precise compliance levels and features we support (for documentation); see below
2. modify regex pattern for validation that reflects 1, or that tightens the validation beyond current
3. long-term status …
> (input): Add EDTF as an option for date representation

- schemas/styles/csl-choose.rnc
- schemas/styles/csl-terms.rnc
This changes `sub verbo` to `sub-verbo` so this will be testable as is.
> add locator term sub-verbo, remove legacy workaround

- schemas/styles/csl-terms.rnc
Used for styles that switch to an abbreviated `citation-label` format for subsequent citations.
Long and short forms might be localized as "henceforth cited as" and "henceforth" respectively.
Closes https://github.com/citation-style-language/csl-evolution/issues/37
> Add henceforth term

- csl-terms.rnc
Adding these to Punctuation will enable using different punctuation marks as default in styles for languages like Arabic and Persian. Without the different commas and semicolons, citations are difficult to read and directionality is impacted, adding unneeded complexity in the final editing process.
> Added comma and semicolon

- schemas/styles/csl.rnc
There same to be more page range formats than the one that we currently support. E.g. (as per #123):
* The [MHRA format](http://www.mhra.org.uk/Publications/Books/StyleGuide/StyleGuideV3_1.pdf) (see p. 47 of the guide), which is like `chicago` but wants a leading zero, e.g. 13–15, 44–47, 100–22, 104–08, 1933–39 but 1098–1101.
* The [OUP format](http://global.oup.com/uk/academic/authors/AuthorGuidelinesMain/HouseStyle/#lev20), which is like the `minimal` style but requests, 'Do not omit digits between 10 and 19 in any hundred.’ I believe this is supposed to fit with English pronunciation (cf. a [similar style guide](http://www.pims.ca/pdf/bw-stylesheet.pdf)).
Closes #123 
> add new page-range formats

- schemas/input/csl-data.json
- tests/schemas/input/test_json.py
This modifies the structured date object to align with the EDTF model.
It moves the qualifiers to the date object, and then defines a date
range as an array of these date objects.
The result is that dates can either be represented as an EDTF string, 
or as a structured object date, or a date range array.
The intention is this structured variant will go away in time, so that 
in the future the only option will be the EDTF string.
Closes #300 
-----
In CSL JSON 1.0, dates are either a two-level nested array ...
``` js
"issued": {
"date-parts": [
[
2000,
3,
15
],
[
2000,
3,
17
]
],
"circa": "true"
}
```
... or a `raw` string, with is a standard EDTF-like date (note, however, that the example isn't compliant because months are not two-digits, as they are in ISO 8601).
``` js
"accessed": { …
```
> input: Align date-parts and edtf string models

- README.md
Update link to Jing in README.md as they moved from Google Code to GitHub.
It is a tiny change in the README file.
> Update link to Jing in README.md

- schemas/input/csl-data.json
The CSL 1.0 style schema adopted a flat key-value data model for standard variables like titles and identifiers.
The 1.0 JSON schema was designed to provide a machine-readable way to feed CSL processors with a model that matched the style model.
Since then, CSL, and the use of CSL JSON, has exploded, as have the number of feature requests. 
Recent development work put us in a situation where we could have ended up with well over 100 variables to support new features (see #167), which does not seem practical.
This PR aims to make the input schema simpler and more flexible, without needing to add new variables whenever there's a feature request.
> input: Add related-item modelling #268

- schemas/styles/csl.rnc
Alternative PR to #306
Some languages have multiple forms for a term depending on the item type (usually books versus journals). For example, Turkish uses different phrases for "ibid" for books vs. journals. German uses different words for "volume" for books vs. journals.
Instead of using the standard `cs:choose` syntax this PR just adds a new attribute `types` to be used with term definitions.
In styles or locale files this will be used like this:
```xml
<terms>
<term name="volume" types="article article-journal article-magazine article-newspaper">a term</term>
<term name="volume">another term</term>
</terms>
```
Fixes #282 (issue)
> add @types to terms

- schemas/styles/csl.rnc
per https://github.com/citation-style-language/schema/issues/236#issue-635743993:
> Specifically, French typography typically requires a non breaking space here, whereas US typography very much doesn't.
> I.e. `A.&nbsp;Smith` vs. `A. Smith`
> The former is currently impossible in Zotero.
> This should likely be a locale spec
This adds a new locale option `initial-family-name-delimiter`.
Closes #236 
> adds locale option initial-family-name-delimiter

- schemas/input/csl-citation.json
CSL input needs to accommodate possibility of multiple locators. Rather than requiring processors to parse a single string, this adds the structures to properly represent these data.
Example, in YAML
``` yaml
locators: 
- 
page: 23
- 
line: 12
```
This was easy enough to throw together, so I thought I'd post it for comment.
I also added a version property while I was at it.
Do you see any problem with doing this @fbennett?
> input: Convert locator to an object array

- schemas/styles/csl.rnc
In this [discussion](https://discourse.citationstyles.org/t/dropping-cs-substitute/697/52) on discourse, we somehow agreed on introducing general one time rendering, and a forced re-rendering with an attribute `repeatable=true`.
If we indeed introduce this, this will need an addition to the specs and a new attribute for rendering elements.
This PR already adds the required attribute for re-rendering otherwise suppressed variables.
Fixes #287
> Add repeatable attribute to rendering elements

- schemas/styles/csl-choose.rnc
WIP
This will add new test condîtions that require two attributes:
- `@tested`: specifies the variables to be tested
- `@matches`: specifies the variable to be tested against
- `@date-range`: tests if a variable is in a given date range
- `@date-precision`: tests whether certain date parts are present.
Fixes #251 #254  #285 
The patterns lead to duplicate suggestions when using autocompletion. Anyone knows what to do here?
> Add new conditions

- schemas/styles/csl-choose.rnc
- schemas/styles/csl-citation-label-format.rnc
- schemas/styles/csl-data.rnc
- schemas/styles/csl-relaxed.rnc
- schemas/styles/csl-repository.rnc
- schemas/styles/csl-variables.rnc
- schemas/styles/csl.rnc
Add syntax for specifying citation label format. Based on the biblatex label syntax: http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf
It adds a `cs:citation-label-format` element.
It can take either `label-type` attribute to specify one of two prespecified formats or a combination of options attributes and rendering elements to generate a custom format.
Fixes https://github.com/citation-style-language/schema/issues/295
> Add citation-label-format syntax

- schemas/input/csl-data.json
- schemas/styles/csl-types.rnc
- schemas/styles/csl-variables.rnc
Closes https://github.com/citation-style-language/schema/issues/293
Add a `project` type for grants and similar. For example, such items are often cited on CVs and grant applications.
@bdarcus You said in the linked thread "supporting grants would require more than just a type and creator variable". What else were you thinking? I think the other existing variables (publisher, genre, number, status) covers things.
> Add type and creator variables for grants/projects

- schemas/input/csl-data.json
Per @fbennett, these are no longer needed for contributor names. 
See:
https://github.com/citation-style-language/documentation/pull/39#issuecomment-667672082
https://github.com/citation-style-language/documentation/pull/39#issuecomment-667757772
> input: Remove static-ordering and comma-suffix

- schemas/input/csl-data.json
- schemas/styles/csl-variables.rnc
If we indeed plan to add a `language-alternate` object to the title object, we should not add ` translated-title` in 1.0.2. So this PR removes this variables again.
> remove translated-title

- schemas/input/csl-citation.json
See #347. This implements the simple change.
Also addresses #241 by adding an annotation for `id`.
> input: Move noteIndex to main object properties

- schemas/input/csl-data.json
- schemas/styles/csl-choose.rnc
This aligns range representation for dates with ranges in locators (see #326).
``` js
"issued": {
"begin": { "year": 2000 },
"end": { "year": 2001 }
}
```
Note: assuming no objections , I'll probably want to fix some of the formatting so it's relatively compact and consistent, along with the test code for dates so CI passes.
> input: Change date range from array to object

- schemas/styles/csl-variables.rnc
The variable `event` is marked as deprecated already. Should be removed in 1.1.
> Remove deprecated event variable

- schemas/styles/csl.rnc
This removes the title-split attribute. That should be no longer necessary since titles are now objects.
Fixes #366 
(This also corrects a typo and adds an `" : "` to `normalize-title-delimiters="simple"`)
> Remove title split

- schemas/input/csl-data.json
- schemas/styles/csl-variables.rnc
Some role variables (e.g. `editor` and `translator`) can relate to title variables on multiple levels: `title`, `container-title`, `volume-title`, `collection-title`, i.e., multi-volume publications can have editors for the whole publication, and also editors for specific volumes. 
Currently, we have only one translator variable, and two editor variables: `editor` and `collection-editor`, so we're not able to deal with this complexity properly.
This PR adds new role variables: `volume-editor`, and `volume-translator`, `container-translator`.
This should be RTM.
Partially closes #289 
Should this also deal with the "editor@title vs. editor@container-title" case? Currently, styles use conditionals à la `if type="chapter ..."` to deal with this.
- …
> Add `volume-editor` and `volume-translator`

- schemas/styles/csl-terms.rnc
The introduction of `editor-translator` as a testable name variable makes the `editortranslator` term redundant.
> remove term

- schemas/styles/csl.rnc
Allows locales to specify the alphabet set to use for year-suffixes.
Fixes https://github.com/citation-style-language/schema/issues/136
> Make year suffix localizable

- schemas/styles/csl.rnc
This makes `@form` optional on `cs:text` with `@variable`.
> make @form optional on cs:text with @variable

- .github/workflows/test.yaml
The GitHub workflow XML test job is failing because of an error 
installing a dependency. This fixes it.
> Add apt-get update to XML test

- .github/workflows/test.yaml
- schemas/styles/csl.rnc
Based on discussion re: https://github.com/citation-style-language/documentation/pull/115, add `chicago-15` and `chicago-16` page range formats.
Chicago changed its page range collapse rules in 16th edition. CSL currently follows 15th edition rules. This PR adds specific formats for the two versions. For 1.0.2, `chicago` will keep its current meaning and be an alias for `chicago-15`. In 1.1 and later, it will change to be an alias for `chicago-16`.
Fixes # (issue)
> Add chicago page range variants

- schemas/input/csl-citation.json
For custom special locator types (e.g., "Psalms 4:3–6"). No label is applied to string. After realizing that pandoc has a way to distinguish these from suffixes (https://github.com/citation-style-language/schema/issues/94#issuecomment-651167640), I don't see a problem with this existing.
Closes https://github.com/citation-style-language/schema/issues/94
> Add string locator type

- schemas/input/csl-data.json
These are now stored as the "short" property of each "title" variable.
Fixes https://github.com/citation-style-language/schema/issues/113#issuecomment-672834744
> Remove redundant short title properties from JSON schema

- schemas/styles/csl-variables.rnc
- schemas/styles/csl.rnc
This makes `@form` optional again. With this change 1.0 styles can again be validated.
Edit: This also re-adds `title-short` and `container-title-short`.
Question: How can I now check how that compares to 1.0.1?
> Bugfixes for 1.0.2

- schemas/styles/csl.rnc
Tasks:
1. [X] moved two separate duplicate "and" patterns into a separate one
2. [X] add "none" as option
3. [X] run formatting
4. [ ] test
Close #402.
> Add "none" option for 'and' attribute

- schemas/styles/csl.rnc
Adds a style attribute specifying that `https://` and `http://` should be stripped from rendered URLs. 
Fixes [# (issue)](https://github.com/citation-style-language/schema/issues/395)
> Strip protocol

- schemas/input/csl-data.json
The JSON Schema csl-data.json misses recommended field `type` at two places. Most validators can make use of the schemas as they are but at least ajv with https://ajv.js.org/strict-mode.html complains.
> Add missing type field to JSON Schema csl-data
